### ISSUE TITLE
VR issues with IAM_API

### ISSUE THREAD

**Issue by deeeep** [jeancarl/node-red-contrib-tjbot#5]
I can not get the TJbot to use the See module in NodeRed due to a change in the underlying APIkey…. 

My gut feeling: change the tjbot.js file with this:
https://github.com/ibmtjbot/tjbot/issues/98
on this file: /home/pi/.node-red/nodes/node-red-contrib-tjbot/node_modules/tjbot/lib/tjbot.js

but I have a feeling that the interface for the APIkey also needs to be adjusted or a field added for the IAM_APIkey…. Where do I do this?

Regards
Deepak

**Comment by deeeep** [comment]
Just changing the code does nothing... but when I try to add a field to the config.html and config.js the whole flow explodes and does not load anymore…

**Comment by lgbaeza** [comment]
I already have this solved, would you give me permission to create a branch and send my pull request?  I also updated the core dependency tjbot

**Comment by ShibuyaS** [comment]
lgbaeza,
Could you tell me a solution for this issue? It is appreciated if you describe that on this thread.

**Comment by jeancarl** [comment]
IAM API key support has been implemented for all the Watson services. Issue should be fixed.
