### ISSUE TITLE
user name for tts is not being saved.

### ISSUE THREAD

**Issue by uncommonman** [jeancarl/node-red-contrib-tjbot#9]
Looks like there is a line missing in config.html, since the user name is not saved for the Text To Speech service. The lines

      ttsPassword: {type:"password"},
      sttUsername: {type:"text"},
      sttPassword: {type:"password"},

should probably be

      ttsUsername: {type:"text"},
      ttsPassword: {type:"password"},
      sttUsername: {type:"text"},
      sttPassword: {type:"password"},

**Comment by jeancarl** [comment]
This issue should be fixed.
